// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppkyhlpovlbovubbvjby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwa3lobHBvdmxib3Z1YmJ2amJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzI1NTgsImV4cCI6MjA1OTM0ODU1OH0.c5wWTocRivuqq6ocP9HGaL5YNCQHLzaphN5iYgLlL00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);